image: docker:git

services:
  - docker:dind

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export COMMITS=$(git rev-list --all --count)
  - export LATEST_VERSION=$(git describe --tags)
cache:
  paths:
    - .gradle/wrapper

gradle-build:
  stage: build
  image: openjdk:14-jdk
  script: "./gradlew build -x test"
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

docker-build:
  stage: package
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CI_REGISTRY_IMAGE:$LATEST_VERSION -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$LATEST_VERSION

docker-build-staging:
  stage: package
  only:
    - staging
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:staging || true
    - docker build --cache-from $CONTAINER_IMAGE:staging -t $CI_REGISTRY_IMAGE:$LATEST_VERSION-staging -t $CI_REGISTRY_IMAGE:staging .
    - docker push $CI_REGISTRY_IMAGE:staging
    - docker push $CI_REGISTRY_IMAGE:$LATEST_VERSION-staging

create-badges:
  stage: build
  image: python:3.6.6
#  only:
#    - master
  script:
    - echo "Python other dependencies installation"
  after_script:
    - pip install anybadge
    - echo commits $COMMITS latest_version $LATEST_VERSION
    - anybadge -o -l "latest version" -v $LATEST_VERSION -f latestversion.svg -c green
    - anybadge -o -l "commits" -v $COMMITS -f commits.svg -c lightgrey
    - anybadge -o -l "licence" -v "Apache License" -f license.svg -c yellowgreen
    - anybadge -o -l "awesomeness" -v "110%" -f awesomeness.svg -c orange
  artifacts:
    paths:
      - commits.svg
      - latestVersion.svg
