spring:
  application:
    name: docsrabbit
  data:
    mongodb:
      database: ${MONGO_DATABASE:docsrabbit}
      uri: ${MONGO_URI:mongodb://localhost:27017/docsrabbit}
  servlet:
    multipart:
      max-file-size: 100MB

server:
  port: 50005

management:
  server:
    port: 51005

docsrabbit:
  pdf:
    default-template: default.ftlh
  xls:
    default-template: default.xls
