docsrabbit:
  pdf:
    default-template: default.ftlh
spring:
  application:
    name: docsrabbit
  data:
    mongodb:
      database: ${MONGO_DATABASE:docsrabbit}
      uri: ${MONGO_URI:mongodb://localhost:27017/docsrabbit}
server:
  port: 50005
management:
  server:
    port: 50006